### ISSUE TITLE
About training and evaluation dataset

### ISSUE THREAD

**Issue by yvaine** [mpkuse/cartwheel_train#5]
Hi, mpkuse
thank you for your job very much.  I still have two  questions. 
1. Why not use TokyoTM as training dataset?
2. What is Pitssburg_validation dataset ?
Wish for your reply! Thank you!

**Comment by mpkuse** [comment]
Hi Yvaine,
You could use TokyoTM. I have setup parser for it. So specific reason I went for Pittsburg. 

Pittsbug has 10 folders 000 to 010. I kept last 2 in a separate folder and trained just with 8. I used 2 for validation every epoch. 

I hope this answers your question.
